1. How to import pandas and check the version?

In [3]:
import pandas as pd
print(pd.__version__)

2.2.2


2. How to create a series from a list, numpy array and dict?

In [10]:
import numpy as np
mylist=list("abcdefghijklmnopqrstuvwxyz")
myarr=np.arange(26)
mydict=dict(zip(mylist,myarr))

print(pd.Series(mylist).head())
print(pd.Series(myarr).head())
print(pd.Series(mydict).head())


0    a
1    b
2    c
3    d
4    e
dtype: object
0    0
1    1
2    2
3    3
4    4
dtype: int64
a    0
b    1
c    2
d    3
e    4
dtype: int64


3. How to convert the index of a series into a column of a dataframe?

In [11]:
ser=pd.Series(mydict)
df=ser.to_frame().reset_index()
print(df)

   index   0
0      a   0
1      b   1
2      c   2
3      d   3
4      e   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25


4. How to combine many series to form a dataframe?

In [15]:
ser1=pd.Series(list("abcdefghijklmnopqrstuvwxyz"))
ser2=pd.Series(np.arange(26))
df=pd.DataFrame({'c1':ser1,"c2":ser2})
print(df.head())

  c1  c2
0  a   0
1  b   1
2  c   2
3  d   3
4  e   4


5. How to assign name to the series’ index?

In [20]:
ser=pd.Series(list("abcdefghijklmnopqrstuvwxyz"))
ser.name="alphabets"
print(ser.head())

0    a
1    b
2    c
3    d
4    e
Name: alphabets, dtype: object


7. How to get the items not common to both series A and series B?

In [24]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
s1=set(ser1)
s2=set(ser2)
res=s1.symmetric_difference(s2)
print(res)

{1, 2, 3, 6, 7, 8}


8. How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?

In [28]:
ser = pd.Series(np.random.normal(10, 5, 25))
print("minimum:",ser.min())
print("25th percentile:",ser.quantile(0.25))
print("median:",ser.median())
print("75th percentile:",ser.quantile(0.75))
print("maximum:",ser.max())

minimum: 0.12966039212199476
25th percentile: 6.862687426527527
median: 8.426893079761792
75th percentile: 11.728333904128037
maximum: 23.169906832067227


9. How to get frequency counts of unique items of a series?

In [31]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
print(ser.value_counts())

b    7
h    5
a    4
d    4
g    3
f    3
c    2
e    2
Name: count, dtype: int64


10. How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?

In [34]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
top_2=ser.value_counts().nlargest(2).index
res=ser.where(ser.isin(top_2),other='other')
print(res)

0         4
1         4
2     other
3         3
4         3
5         4
6         3
7         4
8     other
9         4
10    other
11        3
dtype: object


11. How to bin a numeric series to 10 groups of equal size?

In [39]:
ser = pd.Series(np.random.random(20))
# print(ser.head())
print(pd.qcut(ser,10,labels=[f'{i+1}th' for i in range(10)]))

0      4th
1      3th
2      2th
3      3th
4     10th
5      7th
6      5th
7      5th
8      1th
9      4th
10     8th
11     9th
12     6th
13     8th
14     1th
15     9th
16     2th
17     7th
18    10th
19     6th
dtype: category
Categories (10, object): ['1th' < '2th' < '3th' < '4th' ... '7th' < '8th' < '9th' < '10th']


12. How to convert a numpy array to a dataframe of given shape? (L1)

In [45]:
ser = pd.Series(np.random.randint(1, 10, 35))
reshape_ser=ser.values.reshape((7,5))
print(reshape_ser)

[[2 2 2 9 7]
 [8 1 4 6 6]
 [1 9 7 8 7]
 [7 8 3 2 1]
 [9 7 3 7 1]
 [6 6 1 1 7]
 [3 2 9 2 7]]


13. How to find the positions of numbers that are multiples of 3 from a series?

In [51]:
import numpy as np
ser = pd.Series(np.random.randint(1, 10, 7))
print(np.argwhere(ser%3==0))

[[1]
 [5]]


14. How to extract items at given positions from a series

In [53]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
for i in pos:
    print(ser[i])
    #or
ser.take(pos)

a
e
i
o
u


0     a
4     e
8     i
14    o
20    u
dtype: object

15. How to stack two series vertically and horizontally ?

In [59]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
df=pd.DataFrame({"index":ser1,"value":ser2})
print(df)
# ser1.append(ser2)
df=pd.concat([ser1,ser2],axis=1)
print(df)

   index value
0      0     a
1      1     b
2      2     c
3      3     d
4      4     e
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


16. How to get the positions of items of series A in another series B?

In [70]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
ind=[pd.Index(ser1).get_loc(i) for i in ser2]
print(ind)

[5, 4, 0, 8]


17. How to compute the mean squared error on a truth and predicted series?

In [72]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
# print(truth.head())
# print(pred.head())
print((sum(truth-pred)**2)/len(truth))

0    0
1    1
2    2
3    3
4    4
dtype: int64
0    0.497334
1    1.226948
2    2.058249
3    3.818912
4    4.475112
dtype: float64
1.9133179446881925


18. How to convert the first character of each element in a series to uppercase?

In [75]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
l1=[]
for i in range(len(ser)):
    l1.append(ser[i][0].upper()+ser[i][1:])
print(l1)

['How', 'To', 'Kick', 'Ass?']


19. How to calculate the number of characters in each word in a series?

In [79]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
res=ser.map(lambda val :len(val))
print(res)


0    3
1    2
2    4
3    4
dtype: int64


20. How to compute difference of differences between consequtive numbers of a series?

In [89]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
print(ser.diff().diff())

0    NaN
1    NaN
2    1.0
3    1.0
4    1.0
5    1.0
6    0.0
7    2.0
dtype: float64


21. How to convert a series of date-strings to a timeseries?

In [88]:
from dateutil.parser import parse
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
ser_parse=ser.map(lambda x:parse(x))
print(pd.to_datetime(ser_parse))

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]


22. How to get the day of month, week number, day of year and day of week from a series of date strings?

In [97]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))
print("Date: ", ser_ts.dt.day.tolist())
print("Week number: ", ser_ts.dt.isocalendar().week.tolist())#learned
print("Day number of year: ", ser_ts.dt.dayofyear.tolist())
print("Day of week: ", ser_ts.dt.day_name().tolist())#learned

Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day number of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


23. How to convert year-month string to dates corresponding to the 4th day of the month?

In [103]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
from dateutil.parser import parse 
set_set=ser.map(lambda x:parse(x).replace(day=4))
print("dates taht start with 4th of each month:",set_set)

dates taht start with 4th of each month: 0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]


24. How to filter words that contain atleast 2 vowels from a series?

In [104]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
res= ser[ser.str.findall(r'[aeiouAEIOU]').str.len()>=2]
print(res)

0     Apple
1    Orange
4     Money
dtype: object


25. How to filter valid emails from a series?

In [107]:
import re

emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
l=[]
for i in range(len(emails)):
    if "@" in emails[i]:
        l.append(emails[i])
print(l)
#or
print(emails.str.findall(pattern,re.IGNORECASE))

['rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']
0                     []
1    [rameses@egypt.com]
2            [matt@t.co]
3    [narendra@modi.com]
dtype: object


26. How to get the mean of a series grouped by another series?

In [114]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())
fruits_weights_df=pd.DataFrame({"fruits":fruit,"weights":weights})
print(fruits_weights_df)
fruits_weights_df.groupby("fruits").mean("weights")


[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['apple', 'apple', 'banana', 'banana', 'apple', 'apple', 'carrot', 'apple', 'carrot', 'apple']
   fruits  weights
0   apple      1.0
1   apple      2.0
2  banana      3.0
3  banana      4.0
4   apple      5.0
5   apple      6.0
6  carrot      7.0
7   apple      8.0
8  carrot      9.0
9   apple     10.0


weights
fruits          
apple   5.333333
banana  3.500000
carrot  8.000000

27. How to compute the euclidean distance between two series?WITHOUT USING PACKAGED FORMULA(SQRT(X2-X1)**2+(Y2-Y1)**2)

In [121]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
e_dist=np.linalg.norm(p-q)
print(e_dist)

18.16590212458495


28. How to find all the local maxima (or peaks) in a numeric series?

In [123]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
# res=[]
# for i in range(len(ser)):
#     if ser[i-1]<ser[i] and ser[i+1]<ser[i]:
#         res.append(ser.index(i))
# print(res)
dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd == -2)[0] + 1
peak_locs


array([1, 5, 7])

29. How to replace missing spaces in a string with the least frequent character?

In [132]:

from collections import Counter
my_str = 'dbc deb abed gade'
res= Counter(my_str)
res=min(res,key=res.get)
print(my_str.replace(" ",res))


dbccdebcabedcgade


30. How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?

In [139]:
dates=pd.date_range("2000-01-01",periods=10,freq="W-SAT")
values=np.random.randint(0,10,size=10)

df=pd.Series(values,index=dates)
print(df)

2000-01-01    3
2000-01-08    8
2000-01-15    2
2000-01-22    7
2000-01-29    7
2000-02-05    0
2000-02-12    9
2000-02-19    6
2000-02-26    7
2000-03-04    5
Freq: W-SAT, dtype: int64


31. How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?

In [5]:
import numpy as np

In [7]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)
# Input
ser = pd.Series([1,10,3, np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))

# Solution
ser.resample('D').ffill()  # fill with previous value

# Alternatives
ser.resample('D').bfill()  # fill with next value
ser.resample('D').bfill().ffill()  # fill next else prev value

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64


2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

32. How to compute the autocorrelations of a numeric series?

In [8]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
# Input
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

# Solution
autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
print(autocorrelations[1:])
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:]))+1)

[np.float64(-0.05), np.float64(0.28), np.float64(0.02), np.float64(0.23), np.float64(-0.1), np.float64(0.22), np.float64(0.14), np.float64(0.44), np.float64(-0.27), np.float64(0.59)]
Lag having highest correlation:  10


33. How to import only every nth row from a csv file to create a dataframe?

In [9]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.DataFrame()
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])


# Solution 2: Use chunks and list comprehension
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.concat([chunk.iloc[0] for chunk in df], axis=1)
df2 = df2.transpose()

# Solution 3: Use csv reader
import csv          
with open('BostonHousing.csv', 'r') as f:
    reader = csv.reader(f)
    out = []
    for i, row in enumerate(reader):
        if i%50 == 0:
            out.append(row)

df2 = pd.DataFrame(out[1:], columns=out[0])
print(df.head())

AttributeError: 'DataFrame' object has no attribute 'append'

34. How to change column values when importing csv to a dataframe?

In [8]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv',  
                 converters={'medv': lambda x: 'High' if float(x) > 25 else 'Low'})


# Solution 2: Using csv reader
import csv
with open('BostonHousing.csv', 'r') as f:
    reader = csv.reader(f)
    out = []
    for i, row in enumerate(reader):
        if i > 0:
            row[13] = 'High' if float(row[13]) > 25 else 'Low'
        out.append(row)

df = pd.DataFrame(out[1:], columns=out[0])
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'BostonHousing.csv'

35. How to create a dataframe with rows as strides from a given series?

In [3]:
import pandas as pd
import numpy as np

In [5]:
L = pd.Series(range(15))
# L = pd.Series(range(15))

def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

36. How to import only specified columns from a csv file?

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
print(df.head())

      crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2


37. How to get the nrows, ncolumns, datatype, summary stats of each column of a dataframe? Also get the array and list equivalen

In [10]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

#  number of rows and columns
print(df.shape)

# datatypes
print(df.dtypes)

# how many columns under each dtype
# print(df.get_dtype_counts())
print(df.dtypes.value_counts())

# summary statistics
df_stats = df.describe()

# numpy array 
df_arr = df.values

# list
df_list = df.values.tolist()

(93, 27)
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object
float64    18
object      9
Name: count, dtype: int64


38. How to extract the row and column number of a particular cell with given criterion?

In [12]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
# df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
# Get Manufacturer with highest price
df.loc[df.Price == np.max(df.Price), ['Manufacturer', 'Model', 'Type']]

# Get Row and Column number
row, col = np.where(df.values == np.max(df.Price))

# Get the value
df.iat[row[0], col[0]]
df.iloc[row[0], col[0]]

# Alternates
df.at[row[0], 'Price']
df.at[row[0], 'Price']

# The difference between `iat` - `iloc` vs `at` - `loc` is:
# `iat` snd `iloc` accepts row and column numbers. 
# Whereas `at` and `loc` accepts index and column names.

np.float64(61.9)

39. How to rename a specific columns in a dataframe?

In [14]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
# print(df.columns)
df=df.rename(columns = {'Type':'CarType'})
# or
df.columns.values[2] = "CarType"

# Step 2:
df.columns = df.columns.map(lambda x: x.replace('.', '_'))
print(df.columns)

Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


40. How to check if a dataframe has any missing values?

In [16]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.isna().sum()

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags               38
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

41. How to count the number of missing values in each column?

In [19]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
n_missings_each_col = df.apply(lambda x: x.isnull().sum())
a=n_missings_each_col.argmax()
print(a)

8


42. How to replace missing values of multiple numeric columns with the mean?

In [20]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
print(df_out.head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


43. How to use apply function on existing columns with global variables as additional arguments?

In [21]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
d = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))

44. How to select a specific column from a dataframe as a dataframe instead of a series?

In [24]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

type(df[['a']])
type(df.loc[:, ['a']])
type(df.iloc[:, [1]])


pandas.core.frame.DataFrame

45. How to change the order of columns of a dataframe?

In [38]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
print(df)
df["a"],df["c"]=df["c"],df["a"]
print()
print(df)
print()
def interchange_columns(df, col1, col2):
    df = df[[col for col in df.columns if col not in [col1, col2]] + [col1, col2]]
    return df

# Usage example
df = interchange_columns(df, 'a', 'c')
print(df)
print()

df = df[sorted(df.columns, reverse=True)]
print(df)

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

    a   b   c   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

    b   d   e   a   c
0   1   3   4   2   0
1   6   8   9   7   5
2  11  13  14  12  10
3  16  18  19  17  15

    e   d   c   b   a
0   4   3   0   1   2
1   9   8   5   6   7
2  14  13  10  11  12
3  19  18  15  16  17


46. How to set the number of rows and columns displayed in the output?

In [39]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Set display options
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 10)

# Now when you print the DataFrame, it will show a maximum of 10 rows and 10 columns
print(df)

   Manufacturer    Model     Type  Min.Price  Price  ...  Rear.seat.room  \
0         Acura  Integra    Small       12.9   15.9  ...            26.5   
1           NaN   Legend  Midsize       29.2   33.9  ...            30.0   
2          Audi       90  Compact       25.9   29.1  ...            28.0   
3          Audi      100  Midsize        NaN   37.7  ...            31.0   
4           BMW     535i  Midsize        NaN   30.0  ...            27.0   
..          ...      ...      ...        ...    ...  ...             ...   
88   Volkswagen  Eurovan      Van       16.6   19.7  ...            34.0   
89   Volkswagen   Passat  Compact       17.6   20.0  ...            31.5   
90   Volkswagen  Corrado   Sporty       22.9   23.3  ...            26.0   
91        Volvo      240  Compact       21.8   22.7  ...            29.5   
92          NaN      850  Midsize       24.8   26.7  ...            30.0   

    Luggage.room  Weight   Origin                Make  
0            NaN  2705.0  non-U

47. How to format or suppress scientific notations in a pandas dataframe?

In [40]:
# Create the DataFrame
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

# Suppress scientific notation and format to 4 decimal places
pd.options.display.float_format = '{:.4f}'.format

# Print the DataFrame
print(df)


   random
0  0.0000
1  0.0148
2  0.0314
3  0.0000


48. How to format all the values in a dataframe as percentages?

In [41]:
df = pd.DataFrame(np.random.random(4), columns=['random'])

# Format the values in the 'random' column as percentages
df['random'] = df['random'].apply(lambda x: f"{x * 100:.2f}%")

# Print the DataFrame
print(df)


   random
0  52.19%
1  89.77%
2  20.79%
3  81.99%


49. How to filter every nth row in a dataframe?


In [42]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Filter every 20th row starting from the 1st row (row 0)
filtered_df = df.iloc[::20][['Manufacturer', 'Model', 'Type']]

# Print the filtered DataFrame
print(filtered_df)


   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


50. How to create a primary key index by combining relevant columns?

In [43]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0, 1, 2, 3, 5])

# Replace NaNs with 'missing' in the specified columns
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')

# Create a new index by combining the three columns
df['PrimaryKey'] = df['Manufacturer'] + '_' + df['Model'] + '_' + df['Type']
df.set_index('PrimaryKey', inplace=True)

# Check if the index is unique (to confirm it can be a primary key)
is_unique = df.index.is_unique

# Print the DataFrame with the new index and the uniqueness check
print(df)
print("\nIs the index a primary key? ", is_unique)

                          Manufacturer    Model     Type  Min.Price  Max.Price
PrimaryKey                                                                    
Acura_Integra_Small              Acura  Integra    Small    12.9000    18.8000
missing_Legend_Midsize         missing   Legend  Midsize    29.2000    38.7000
Audi_90_Compact                   Audi       90  Compact    25.9000    32.3000
Audi_100_Midsize                  Audi      100  Midsize        NaN    44.6000
BMW_535i_Midsize                   BMW     535i  Midsize        NaN        NaN
...                                ...      ...      ...        ...        ...
Volkswagen_Eurovan_Van      Volkswagen  Eurovan      Van    16.6000    22.7000
Volkswagen_Passat_Compact   Volkswagen   Passat  Compact    17.6000    22.4000
Volkswagen_Corrado_Sporty   Volkswagen  Corrado   Sporty    22.9000    23.7000
Volvo_240_Compact                Volvo      240  Compact    21.8000    23.5000
missing_850_Midsize            missing      850  Mid

51. How to get the row number of the nth largest value in a column?

In [44]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10, -1), columns=list('abc'))

# Display the DataFrame
print("DataFrame:\n", df)

# Find the row position of the 5th largest value in column 'a'
n = 5
row_position = df['a'].nlargest(n).index[-1]

# Print the row position
print(f"The row position of the {n}th largest value in column 'a' is: {row_position}")

DataFrame:
     a   b   c
0  16  14  21
1   1  12  10
2   9   7  16
3  25  11  25
4  18   3  24
5  21   5   7
6  19  16  24
7  28  20   4
8  15   4  27
9   8  20  27
The row position of the 5th largest value in column 'a' is: 4


52. How to find the position of the nth largest value greater than a given value?

In [45]:
ser = pd.Series(np.random.randint(1, 100, 15))

# Display the Series
print("Series:\n", ser)

# Calculate the mean of the Series
mean_value = ser.mean()

# Find the 2nd largest value greater than the mean
n = 2
greater_than_mean = ser[ser > mean_value]

# Check if there are enough values greater than the mean
if len(greater_than_mean) >= n:
    nth_largest_value = greater_than_mean.nlargest(n).iloc[-1]
    position = ser[ser == nth_largest_value].index[0]
    print(f"The position of the {n}th largest value greater than the mean ({mean_value:.2f}) is: {position}")
else:
    print(f"There are not enough values greater than the mean ({mean_value:.2f}) to find the {n}th largest.")

Series:
 0     22
1     80
2     89
3     57
4     40
      ..
10    36
11    85
12    32
13     5
14    95
Length: 15, dtype: int64
The position of the 2th largest value greater than the mean (47.20) is: 2


53. How to get the last n rows of a dataframe with row sum > 100?

In [46]:
df = pd.DataFrame(np.random.random((10, 5)) * 50)  # Random values scaled to 50

# Display the original DataFrame
print("Original DataFrame:\n", df)

# Calculate the row sums
row_sums = df.sum(axis=1)

# Filter the rows where the row sum is greater than 100
filtered_df = df[row_sums > 100]

# Get the last 2 rows of the filtered DataFrame
last_n_rows = filtered_df.tail(2)

# Print the result
print("\nLast two rows with row sum > 100:\n", last_n_rows)

Original DataFrame:
         0       1       2       3       4
0 19.4772 37.5673  5.4044 46.2351 35.1521
1 22.8742 13.4369 44.8640 36.9360  6.3377
2  2.4375 20.0304 16.9972 18.4557 41.3944
3  4.7236  0.8923 16.8762 46.7345 37.6457
4 27.0146  1.6861 31.9196  6.3409 25.2919
5 37.2934 30.2530  5.2751 24.3968 39.8408
6 19.4777 18.3682 45.4225  4.0004  9.0360
7 26.5043 27.5425 37.9644 14.3159 47.9884
8 18.5867 21.7720 37.2602 20.1120  8.7779
9 10.0472 43.3514 20.6474 13.3082  8.6725

Last two rows with row sum > 100:
         0       1       2       3       4
7 26.5043 27.5425 37.9644 14.3159 47.9884
8 18.5867 21.7720 37.2602 20.1120  8.7779


54. How to find and cap outliers from a series or dataframe column?


In [47]:
ser = pd.Series(np.logspace(-2, 2, 30))

# Display the original Series
print("Original Series:\n", ser)

# Calculate the 5th and 95th percentiles
lower_bound = ser.quantile(0.05)
upper_bound = ser.quantile(0.95)

# Cap the outliers
ser_capped = ser.copy()  # Make a copy to preserve original data
ser_capped[ser_capped < lower_bound] = lower_bound
ser_capped[ser_capped > upper_bound] = upper_bound

# Print the capped Series
print("\nCapped Series:\n", ser_capped)

# Optionally, display the bounds for reference
print(f"\nLower 5th percentile: {lower_bound}")
print(f"Upper 95th percentile: {upper_bound}")

Original Series:
 0      0.0100
1      0.0137
2      0.0189
3      0.0259
4      0.0356
       ...   
25    28.0722
26    38.5662
27    52.9832
28    72.7895
29   100.0000
Length: 30, dtype: float64

Capped Series:
 0     0.0160
1     0.0160
2     0.0189
3     0.0259
4     0.0356
       ...  
25   28.0722
26   38.5662
27   52.9832
28   63.8767
29   63.8767
Length: 30, dtype: float64

Lower 5th percentile: 0.016049294076965887
Upper 95th percentile: 63.87667222018393


55. How to reshape a dataframe to the largest possible square after removing the negative values?

In [48]:
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10, -1))

# Display the original DataFrame
print("Original DataFrame:\n", df)

# Flatten the DataFrame and filter out negative values
positive_values = df.values[df.values >= 0]

# Determine the size of the largest possible square
n = int(np.floor(np.sqrt(len(positive_values))))

# Create a new square DataFrame with the positive values
reshaped_df = pd.DataFrame(positive_values[:n**2].reshape(n, n))

# Display the reshaped DataFrame
print("\nReshaped DataFrame to largest possible square:\n", reshaped_df)

Original DataFrame:
     0   1   2   3   4   5   6   7   8   9
0  -1 -10  -8 -14  19   3   6  -2 -10  -2
1  -7  21 -20  38  47  47  35 -11  42 -12
2  33 -18  49  17  32   8   6  -8  -8  34
3   1  36  38  26  41  46  -5   2  32  39
4  14  44  -1  19  30  49  46  37  18  33
5  24  10  20  -1  43 -18  33  19  18  22
6  25   7  24 -12  -5   1  36   3 -11   1
7 -17 -15   8  48  35   4  29   6  39 -19
8  16  34  17  22   3  11   6  -8 -10  -1
9  40  -6  47 -14  -6  11  34  -6  33 -15

Reshaped DataFrame to largest possible square:
     0   1   2   3   4   5   6   7
0  19   3   6  21  38  47  47  35
1  42  33  49  17  32   8   6  34
2   1  36  38  26  41  46   2  32
3  39  14  44  19  30  49  46  37
4  18  33  24  10  20  43  33  19
5  18  22  25   7  24   1  36   3
6   1   8  48  35   4  29   6  39
7  16  34  17  22   3  11   6  40


56. How to swap two rows of a dataframe?

In [49]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

# Display the original DataFrame
print("Original DataFrame:\n", df)

# Swap rows 1 and 2
df.iloc[[1, 2]] = df.iloc[[2, 1]].values

# Display the DataFrame after swapping
print("\nDataFrame after swapping rows 1 and 2:\n", df)

Original DataFrame:
     0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

DataFrame after swapping rows 1 and 2:
     0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


57. How to reverse the rows of a dataframe?


In [50]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

# Display the original DataFrame
print("Original DataFrame:\n", df)

# Reverse the rows of the DataFrame
reversed_df = df[::-1].reset_index(drop=True)

# Display the DataFrame after reversing the rows
print("\nDataFrame after reversing the rows:\n", reversed_df)

Original DataFrame:
     0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

DataFrame after reversing the rows:
     0   1   2   3   4
0  20  21  22  23  24
1  15  16  17  18  19
2  10  11  12  13  14
3   5   6   7   8   9
4   0   1   2   3   4


58. How to create one-hot encodings of a categorical variable (dummy variables)?

In [53]:
df = pd.DataFrame(np.arange(25).reshape(5, -1), columns=list('abcde'))

# Display the original DataFrame
print("Original DataFrame:\n", df)

# Get one-hot encodings for column 'a'
one_hot = pd.get_dummies(df['a'])

# Append the one-hot encodings to the original DataFrame
df_with_dummies = pd.concat([one_hot, df.drop('a', axis=1)], axis=1)

# Display the DataFrame with one-hot encodings
print("\nDataFrame with one-hot encodings:\n", df_with_dummies)

Original DataFrame:
     a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

DataFrame with one-hot encodings:
        0      5     10     15     20   b   c   d   e
0   True  False  False  False  False   1   2   3   4
1  False   True  False  False  False   6   7   8   9
2  False  False   True  False  False  11  12  13  14
3  False  False  False   True  False  16  17  18  19
4  False  False  False  False   True  21  22  23  24


59. Which column contains the highest number of row-wise maximum values?

In [56]:
# df = pd.DataFrame(np.random.randint(1, 100, 40).reshape(10, -1))
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
# Display the original DataFrame
print('Column with highest row maxes: ', df.apply(np.argmax, axis=1).value_counts().index[0])

Column with highest row maxes:  2


60. How to create a new column that contains the row number of nearest column by euclidean distance?

In [57]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))

# Solution
import numpy as np

# init outputs
nearest_rows = []
nearest_distance = []

# iterate rows.
for i, row in df.iterrows():
    curr = row
    rest = df.drop(i)
    e_dists = {}  # init dict to store euclidean dists for current row.
    # iterate rest of rows for current row
    for j, contestant in rest.iterrows():
        # compute euclidean dist and update e_dists
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})
    # update nearest row to current row and the distance value
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))

df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance

61. How to know the maximum possible correlation value of each column against other columns?

In [58]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
df

# Solution
abs_corrmat = np.abs(df.corr())
max_corr = abs_corrmat.apply(lambda x: sorted(x)[-2])
print('Maximum Correlation possible for each column: ', np.round(max_corr.tolist(), 2))

Maximum Correlation possible for each column:  [0.61 0.52 0.5  0.37 0.61 0.56 0.59 0.55 0.65 0.65]


62. How to create a column containing the minimum by maximum of each row?

In [60]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution 1
min_by_max = df.apply(lambda x: np.min(x)/np.max(x), axis=1)

# Solution 2
min_by_max = np.min(df, axis=1)/np.max(df, axis=1)
print(min_by_max)

0   0.1522
1   0.0568
2   0.3222
3   0.1414
4   0.2500
5   0.2444
6   0.0256
7   0.2083
dtype: float64


63. How to create a column that contains the penultimate value in each row?

In [61]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution
out = df.apply(lambda x: x.sort_values().unique()[-2], axis=1)
df['penultimate'] = out
print(df)

    0   1   2   3   4  ...   6   7   8   9  penultimate
0  75  71  99  62  51  ...  89  77  40  33           89
1  33  47  12   1  14  ...  86  27  92  51           86
2  42  98   2  10  99  ...  15  33  85  33           98
3  83   1  36  67  64  ...  59  57   9  26           67
4  26  12  44  91  92  ...   1  98  31  27           92
5  58  13  86  78  26  ...  89  78   7  17           86
6  89  94  38  40  55  ...   6  58  82  59           89
7  44  48  55  77   2  ...  67  84  53  73           77

[8 rows x 11 columns]


64. How to normalize all columns in a dataframe?

In [63]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution Q1
out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))
print(out1)
 

        0       1       2       3       4       5       6       7       8  \
0 -1.7000  1.5100  0.1900  1.5100 -1.5800 -0.5600 -1.2500 -1.1300 -0.4900   
1  1.3000  0.5700  1.1400 -1.0400  0.6000  1.2800  0.4500 -0.0400  0.5800   
2  0.4400 -0.5300  0.6400 -1.0400  1.1400  0.0400  0.2800  0.5300 -1.8400   
3 -0.0500 -0.4300 -1.5100 -0.6400 -0.7300 -1.2700  1.1300  0.5600  0.9800   
4  0.8100  1.1600 -1.0600  1.1100 -0.9100  0.1800  1.0200  1.1300 -0.6300   
5 -1.2100 -1.4700 -0.1900 -0.2000  0.1100 -1.3800 -0.7200  1.1300  0.5800   
6  0.3200 -0.2000  1.2600 -0.5000  1.2000  0.8900 -1.4300 -1.3800 -0.3100   
7  0.0800 -0.6200 -0.4800  0.8000  0.1700  0.8200  0.5200 -0.8100  1.1200   

        9  
0  0.8500  
1 -1.4300  
2  0.5100  
3  0.3600  
4  1.1300  
5  0.3900  
6 -1.5200  
7 -0.2900  


65. How to compute the correlation of each row with the suceeding row?

In [64]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution
[df.iloc[i].corr(df.iloc[i+1]).round(2) for i in range(df.shape[0])[:-1]]

[np.float64(0.57),
 np.float64(-0.19),
 np.float64(-0.34),
 np.float64(-0.56),
 np.float64(-0.1),
 np.float64(-0.05),
 np.float64(0.55)]

66. How to replace both the diagonals of dataframe with 0?

In [66]:
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))

# Solution
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0
print(df)

    0   1   2   3   4   5   6   7   8   9
0   0  15  48  44  54  57  97  87  28   0
1  60   0  94  54  48  35  79  83   0  84
2  32  74   0  75  30  93  42   0  66  16
3  88  10   4   0  89  72   0  57  69  32
4  37  96  31  46   0   0  40  23  47  70
5  16  19  48  38   0   0  67  10  82  96
6  56  83  30   0  11  33   0  66   7   5
7  73  18   0  91   6   2  77   0  52  38
8  32   0  29  10  83  59  57  60   0  54
9   0  79  26  56  94  34  95  23  98   0


67. How to get the particular group of a groupby dataframe by key?

In [70]:
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])

# # Solution 1
df_grouped.get_group('apple')

# # Solution 2
# for i, dff in df_grouped:
#     if i == 'apple':
#         print(dff)

/tmp/ipykernel_6019/2610414853.py:8: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df_grouped.get_group('apple')


col1   col2  col3
0  apple 0.3775    10
3  apple 0.0667    12
6  apple 0.0681     4

68. How to get the n’th largest value of a column when grouped by another column?

In [71]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

print(df)

# Solution
df_grpd = df['taste'].groupby(df.fruit)
df_grpd.get_group('banana').sort_values().iloc[-2]

    fruit  taste  price
0   apple 0.7082      0
1  banana 0.5014      8
2  orange 0.6591     14
3   apple 0.0440      3
4  banana 0.4346      5
5  orange 0.3087     14
6   apple 0.0377      4
7  banana 0.6571     11
8  orange 0.8687      3


np.float64(0.5013847587551664)

69. How to compute grouped mean on pandas dataframe and keep the grouped column as another column (not index)?

In [72]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

# Solution
out = df.groupby('fruit', as_index=False)['price'].mean()
print(out)

    fruit   price
0   apple 10.6667
1  banana 11.3333
2  orange  4.6667


70. How to join two dataframes by 2 columns so they have only the common rows?

In [74]:

df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

# Solution
pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'], suffixes=['_left', '_right'])

fruit weight  price_left  pazham  kilo  price_right
0   apple   high           9   apple  high           14
1  orange    low           1  orange   low            7
2   apple   high           5   apple  high           14
3  orange    low           0  orange   low            7
4   apple   high          10   apple  high           14
5  orange    low          12  orange   low            7

72. How to get the positions where values of two columns match?


In [75]:
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})

# Solution
np.where(df.fruit1 == df.fruit2)

(array([1, 2, 9]),)

73. How to create lags and leads of a column in a dataframe?


In [76]:
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))

# Solution
df['a_lag1'] = df['a'].shift(1)
df['b_lead1'] = df['b'].shift(-1)
print(df)

    a   b   c   d  a_lag1  b_lead1
0  12  37  32  46     NaN  44.0000
1  62  44  20  44 12.0000  11.0000
2  52  11  58  62 62.0000  95.0000
3  86  95  39  62 52.0000  32.0000
4  50  32  78  27 86.0000      NaN


74. How to get the frequency of unique values in the entire dataframe?

In [77]:
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))

# Solution
pd.value_counts(df.values.ravel())

/tmp/ipykernel_6019/52017146.py:4: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(df.values.ravel())


1    5
8    5
4    3
5    2
6    2
3    2
7    1
Name: count, dtype: int64

75. How to split a text column into two separate columns?


In [78]:
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

# Solution
df_out = df.row.str.split(',|\t', expand=True)

# Make first row as header
new_header = df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = new_header
print(df_out)


0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka
